language: android
os:
  - linux
root: false
android:
  components:
    - tools
    - android-29
    - build-tools-29.0.3
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6

before_script:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache
