name: musiq
description: An open and free music player.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  dio: ^3.0.9
  animations: ^1.0.0+5
  provider: ^4.1.2
  get_it: ^4.0.2
  cached_network_image: ^2.2.0+1
  line_awesome_icons: ^1.0.4+2
  shimmer: ^1.1.1
  audio_service: ^0.9.0
  just_audio: ^0.1.10
  rxdart: ^0.24.1
  html_unescape: ^1.0.1+3
  sentry: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

dependency_overrides:
  dartx: any

flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Bold.ttf
          weight: 700
